"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 04:19:55.882826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


APPEND_ONLY = ("auditoria", "aceites", "termos_adesao_aceites", "auditoria_ancoras")

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_ref', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_document_id'), ['document_id'], unique=False)

    op.create_table('auditoria_ancoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('head_event_id', sa.Integer(), nullable=False),
    sa.Column('head_hash', sa.String(length=64), nullable=False),
    sa.Column('tsa_url', sa.String(length=255), nullable=False),
    sa.Column('token_key', sa.String(length=255), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria_cabeca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('ad_object_guid', sa.String(length=36), nullable=True),
    sa.Column('ad_username', sa.String(length=128), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_object_guid'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colaboradores_matricula'), ['matricula'], unique=True)

    op.create_table('tentativas_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tentativas_login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tentativas_login_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tentativas_login_username'), ['username'], unique=False)

    op.create_table('termos_adesao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('published_by', sa.String(length=128), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('requires_acceptance', sa.Boolean(), nullable=False),
    sa.Column('declaration_text', sa.Text(), nullable=False),
    sa.Column('anchor_text', sa.String(length=200), nullable=True),
    sa.Column('anchor_page', sa.Integer(), nullable=False),
    sa.Column('anchor_box', sa.JSON(), nullable=False),
    sa.Column('engine', sa.Enum('NATIVO', 'DOCUSEAL', name='engine', native_enum=False), nullable=False),
    sa.Column('docuseal_template_id', sa.Integer(), nullable=True),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=True),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['tipos_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mfa_totp',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('secret_enc', sa.String(length=255), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_step', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('sessoes',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('object_guid', sa.String(length=36), nullable=False),
    sa.Column('upn', sa.String(length=256), nullable=True),
    sa.Column('dn', sa.String(length=512), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('termos_adesao_aceites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ad_object_guid', sa.String(length=36), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('registered_by', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['termos_adesao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'term_id')
    )
    with op.batch_alter_table('termos_adesao_aceites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_termos_adesao_aceites_employee_id'), ['employee_id'], unique=False)

    op.create_table('documentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.Enum('NATIVO', 'DOCUSEAL', name='engine', native_enum=False), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'DISPONIVEL', 'ASSINADO', 'RECUSADO', 'CANCELADO', name='docstatus', native_enum=False), nullable=False),
    sa.Column('verification_code', sa.String(length=20), nullable=False),
    sa.Column('original_sha256', sa.String(length=64), nullable=True),
    sa.Column('sealed_sha256', sa.String(length=64), nullable=True),
    sa.Column('final_sha256', sa.String(length=64), nullable=True),
    sa.Column('receipt_sha256', sa.String(length=64), nullable=True),
    sa.Column('original_key', sa.String(length=255), nullable=True),
    sa.Column('sealed_key', sa.String(length=255), nullable=True),
    sa.Column('final_key', sa.String(length=255), nullable=True),
    sa.Column('receipt_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('docuseal_submission_id', sa.Integer(), nullable=True),
    sa.Column('docuseal_submitter_id', sa.Integer(), nullable=True),
    sa.Column('docuseal_signing_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['tipos_documento.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'document_type_id', 'competencia', 'original_sha256')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_docuseal_submitter_id'), ['docuseal_submitter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_final_sha256'), ['final_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_receipt_sha256'), ['receipt_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_sealed_sha256'), ['sealed_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_verification_code'), ['verification_code'], unique=True)

    op.create_table('aceites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ad_object_guid', sa.String(length=36), nullable=False),
    sa.Column('ad_username', sa.String(length=128), nullable=False),
    sa.Column('ad_upn', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reauth_method', sa.String(length=32), nullable=False),
    sa.Column('session_ref', sa.String(length=64), nullable=False),
    sa.Column('document_sha256', sa.String(length=64), nullable=False),
    sa.Column('declaration_text', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('evidence_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###

    # Defesa em profundidade (PostgreSQL): trilha de auditoria e aceites são
    # append-only — UPDATE/DELETE são bloqueados no próprio banco.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE OR REPLACE FUNCTION portal_bloqueia_alteracao() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'tabela % é somente-inclusão (append-only)', TG_TABLE_NAME;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        for table in APPEND_ONLY:
            op.execute(
                f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
                f"FOR EACH ROW EXECUTE FUNCTION portal_bloqueia_alteracao()"
            )


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        for table in APPEND_ONLY:
            op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
        op.execute("DROP FUNCTION IF EXISTS portal_bloqueia_alteracao()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aceites')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_verification_code'))
        batch_op.drop_index(batch_op.f('ix_documentos_status'))
        batch_op.drop_index(batch_op.f('ix_documentos_sealed_sha256'))
        batch_op.drop_index(batch_op.f('ix_documentos_receipt_sha256'))
        batch_op.drop_index(batch_op.f('ix_documentos_final_sha256'))
        batch_op.drop_index(batch_op.f('ix_documentos_employee_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_docuseal_submitter_id'))

    op.drop_table('documentos')
    with op.batch_alter_table('termos_adesao_aceites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_termos_adesao_aceites_employee_id'))

    op.drop_table('termos_adesao_aceites')
    op.drop_table('sessoes')
    op.drop_table('mfa_totp')
    op.drop_table('lotes')
    op.drop_table('tipos_documento')
    op.drop_table('termos_adesao')
    with op.batch_alter_table('tentativas_login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tentativas_login_username'))
        batch_op.drop_index(batch_op.f('ix_tentativas_login_at'))

    op.drop_table('tentativas_login')
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colaboradores_matricula'))

    op.drop_table('colaboradores')
    op.drop_table('auditoria_cabeca')
    op.drop_table('auditoria_ancoras')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_document_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_action'))

    op.drop_table('auditoria')
    # ### end Alembic commands ###
